version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/docker/"
    schedule:
      interval: "weekly"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
