ARG UBUNTU_VERSION
FROM ghcr.io/kegustafsson/signalk-server-base:latest-${UBUNTU_VERSION} AS base

USER node
RUN mkdir -p /home/node/.signalk/ \
  && mkdir -p /home/node/signalk/

WORKDIR /home/node/signalk

RUN npm config rm proxy \
  && npm config rm https-proxy \
  && npm config set fetch-retries 5 \
  && npm config set fetch-retry-mintimeout 60000 \
  && npm config set fetch-retry-maxtimeout 120000 \
  && npm cache clean -f

FROM base AS tarballs_installed
WORKDIR /home/node/signalk
COPY --chown=node:node *.tgz .

# Install signalk-server nested (matches signalk-server-X.X.X.tgz, not signalk-server-admin, signalk-server-api, etc.)
RUN npm install $(ls signalk-server-[0-9]*.tgz) --install-strategy=nested

# Install all other tarballs hoisted
RUN for tgz in *.tgz; do \
      case "$tgz" in \
        signalk-server-[0-9]*) ;; \
        *) npm install "./$tgz" ;; \
      esac \
    done

RUN mkdir -p /home/node/signalk/node_modules/signalk-server/node_modules/@signalk/ \
  && cp -rf /home/node/signalk/node_modules/@signalk/* /home/node/signalk/node_modules/signalk-server/node_modules/@signalk/ \
  && rm -rf /home/node/signalk/node_modules/@signalk/

FROM base

COPY --from=tarballs_installed --chown=node:node /home/node/signalk /home/node/signalk

USER node
COPY --chown=node docker/startup.sh startup.sh
RUN chmod +x startup.sh

EXPOSE 3000
ENV IS_IN_DOCKER=true
ENV SKIP_ADMINUI_VERSION_CHECK=true
WORKDIR /home/node/.signalk
ENTRYPOINT ["/home/node/signalk/startup.sh"]
