FROM ghcr.io/kegustafsson/signalk-server-base:latest

ARG TAG
USER node
RUN mkdir -p /home/node/.signalk/ \
  && mkdir -p /home/node/signalk/

WORKDIR /home/node/signalk

RUN npm config rm proxy \
  && npm config rm https-proxy \
  && npm config set fetch-retries 5 \
  && npm config set fetch-retry-mintimeout 60000 \
  && npm config set fetch-retry-maxtimeout 120000 \
  && npm config set registry "https://registry.npmjs.org/" \
  && npm config set @backup:registry "https://registry.yarnpkg.com/" \
  && npm cache clean -f

RUN npm i signalk-server@$TAG \
  && mkdir -p node_modules/signalk-server/node_modules \
  && ln -s /home/node/signalk/node_modules/@signalk /home/node/signalk/node_modules/signalk-server/node_modules/@signalk \
  && rm -rf node_modules/@signalk/ \
  && mkdir -p node_modules/signalk-server/node_modules/@mxtommy/ \
  && cp -rf node_modules/@mxtommy/kip node_modules/signalk-server/node_modules/@mxtommy/ \
  && rm -rf node_modules/@mxtommy/;

COPY --chown=node docker/startup.sh startup.sh
RUN chmod +x startup.sh

EXPOSE 3000
ENV IS_IN_DOCKER=true
WORKDIR /home/node/.signalk
ENTRYPOINT ["/home/node/signalk/startup.sh"]
