ARG NODE
FROM node:${NODE}-alpine

COPY avahi/avahi-dbus.conf bluez/bluezuser.conf /etc/dbus-1/system.d/

RUN apk add --no-cache \
    sudo git bash coreutils \
    python3 py3-virtualenv py3-pip build-base \
    avahi avahi-compat-libdns_sd \
    procps-ng nano curl libcap-setcap dbus bluez \
 && addgroup -g 991 -S docker \
 && addgroup -g 990 -S i2c \
 && addgroup -g 989 -S spi \
 && addgroup node dialout \
 && addgroup node i2c \
 && addgroup node spi \
 && addgroup node netdev \
 && addgroup node docker \
 && echo 'node ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
 && chmod u+s /bin/date \
 && mkdir -p /var/run/dbus /var/run/avahi-daemon \
 && chmod 777 /var/run/dbus /var/run/avahi-daemon \
 && chown -R avahi:avahi /var/run/avahi-daemon

RUN npm config rm proxy \
 && npm config rm https-proxy \
 && npm config set fetch-retries 5 \
 && npm config set fetch-retry-mintimeout 60000 \
 && npm config set fetch-retry-maxtimeout 120000 \
 && npm config set registry "https://registry.npmjs.org/" \
 && npm config set @backup:registry "https://registry.yarnpkg.com/" \
 && npm cache clean -f \
 && npm install -g pm2 \
 && rm -rf /tmp/* /var/tmp/*

WORKDIR /home/node
USER node
