ARG NODE
FROM dhi.io/node:${NODE}-alpine3.23

COPY docker/avahi/avahi-dbus.conf docker/bluez/bluezuser.conf /etc/dbus-1/system.d/

RUN apk add --no-cache \
    sudo git bash \
    python3 py3-virtualenv py3-pip build-base \
    avahi avahi-compat-libdns_sd \
    procps-ng nano curl libcap-setcap dbus bluez

RUN addgroup -g 991 -S docker \
 && addgroup -g 990 -S i2c \
 && addgroup -g 989 -S spi \
 && mkdir -p /var/run/dbus /var/run/avahi-daemon \
 && chmod 777 /var/run/dbus /var/run/avahi-daemon \
 && chown -R avahi:avahi /var/run/avahi-daemon

RUN npm config rm proxy || true \
 && npm config rm https-proxy || true \
 && npm config set fetch-retries 5 \
 && npm config set fetch-retry-mintimeout 60000 \
 && npm config set fetch-retry-maxtimeout 120000 \
 && npm config set registry "https://registry.npmjs.org/" \
 && npm config set @backup:registry "https://registry.yarnpkg.com/" \
 && npm cache clean -f \
 && npm install -g pm2 \
 && rm -rf /tmp/* /var/tmp/*

RUN (getent group node >/dev/null 2>&1 && delgroup node) || true \
 && (getent passwd node >/dev/null 2>&1 && deluser node) || true \
 && addgroup -g 1000 node \
 && adduser  -u 1000 -G node -s /bin/sh -D node \
 && addgroup node dialout || true \
 && addgroup node i2c     || true \
 && addgroup node spi     || true \
 && addgroup node netdev  || true \
 && addgroup node docker  || true

RUN echo 'node ALL=(ALL) NOPASSWD:/bin/date' >> /etc/sudoers \
 && echo 'node ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

WORKDIR /home/node
USER node
