FROM ubuntu:24.04

RUN userdel -r ubuntu \
  && groupadd --gid 1000 node \
  && useradd --uid 1000 --gid node --shell /bin/bash --create-home node

RUN DEBIAN_FRONTEND=noninteractive apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends apt-utils sudo git \
  python3 python3-venv python3-pip build-essential avahi-daemon avahi-discover avahi-utils \
  libnss-mdns mdns-scan libavahi-compat-libdnssd-dev sysstat procps nano curl libcap2-bin dbus bluez \
  && groupadd -r docker -g 991 \
  && groupadd -r i2c -g 990 \
  && groupadd -r spi -g 989 \
  && usermod -a -G dialout,i2c,spi,netdev,docker node \
  && echo 'node ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
  && chmod u+s /usr/bin/date

COPY avahi/avahi-dbus.conf /etc/dbus-1/system.d/avahi-dbus.conf
COPY bluez/bluezuser.conf /etc/dbus-1/system.d/bluezuser.conf

RUN mkdir -p /var/run/dbus/ /var/run/avahi-daemon/ \
  && chmod -R 777 /var/run/dbus/ /var/run/avahi-daemon/ \
  && chown -R avahi:avahi /var/run/avahi-daemon/

RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - \
  && DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends nodejs \
  && npm config rm proxy \
  && npm config rm https-proxy \
  && npm config set fetch-retries 5 \
  && npm config set fetch-retry-mintimeout 60000 \
  && npm config set fetch-retry-maxtimeout 120000 \
  && npm config set registry "https://registry.npmjs.org/" \
  && npm config set @backup:registry "https://registry.yarnpkg.com/" \
  && npm cache clean -f \
  && npm install npm@latest -g \
  && npm install pm2 -g \
  && npm install yarn -g \
  && sudo setcap cap_net_raw+eip $(eval readlink -f `which node`) \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
  