name: SignalK Docker Build 24h

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  check-new-v-tags:
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.check.outputs.proceed }}
    
    steps:
      - name: Fetch and compare tags
        id: check
        run: |
          EXTERNAL_REPO="SignalK/signalk-server"
          tags_response=$(curl -s "https://api.github.com/repos/$EXTERNAL_REPO/tags")
          if [ -z "$tags_response" ] || [ "$tags_response" == "null" ]; then
              echo "Failed to fetch tags from GitHub API."
              exit 1
          fi
          if echo "$tags_response" | jq -e 'type == "object" and has("message")' > /dev/null 2>&1; then
              error_message=$(echo "$tags_response" | jq -r '.message')
              echo "GitHub API error: $error_message"
              exit 1
          fi
          tags_count=$(echo "$tags_response" | jq '. | length')
          if [ "$tags_count" -eq 0 ]; then
              echo "No tags found in repository."
              exit 0
          fi
          echo "Found $tags_count total tags"
          latest_v_tag=""
          latest_v_tag_commit_date=""
          latest_v_tag_commit_sha=""
          for i in $(seq 0 $((tags_count - 1))); do
              tag_name=$(echo "$tags_response" | jq -r ".[$i].name")
              
              # Check if tag starts with 'v'
              if [[ "$tag_name" =~ ^v.* ]]; then
                  latest_v_tag="$tag_name"
                  latest_v_tag_commit_sha=$(echo "$tags_response" | jq -r ".[$i].commit.sha")
                  
                  echo "Found latest v* tag: $latest_v_tag"
                  echo "Commit SHA: $latest_v_tag_commit_sha"
                  break
              fi
          done
          if [ -z "$latest_v_tag" ]; then
              echo "No valid v* tags found."
              exit 0
          fi
          echo "Fetching commit details..."
          commit_details=$(curl -s "https://api.github.com/repos/$EXTERNAL_REPO/commits/$latest_v_tag_commit_sha")
          if [ -z "$commit_details" ] || [ "$commit_details" == "null" ]; then
              echo "Failed to fetch commit details."
              exit 1
          fi
          commit_error=$(echo "$commit_details" | jq -r '.message // empty')
          if [ -n "$commit_error" ]; then
              echo "GitHub API error fetching commit: $commit_error"
              exit 1
          fi
          commit_date=$(echo "$commit_details" | jq -r '.commit.committer.date // .commit.author.date // empty')
          if [ -z "$commit_date" ] || [ "$commit_date" == "null" ]; then
              echo "Failed to extract commit date."
              exit 1
          fi
          echo "Commit date: $commit_date"
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          time_24h_ago=$(date -u -d "$current_time - 24 hours" +"%Y-%m-%dT%H:%M:%SZ")
          commit_epoch=$(date -u -d "$commit_date" +%s)
          current_epoch=$(date -u -d "$current_time" +%s)
          time_diff_seconds=$((current_epoch - commit_epoch))
          days=$((time_diff_seconds / 86400))
          hours=$(( (time_diff_seconds % 86400) / 3600 ))
          minutes=$(( (time_diff_seconds % 3600) / 60 ))
          seconds=$((time_diff_seconds % 60))
          echo "Time difference: ${days}d ${hours}h ${minutes}m ${seconds}s"
          echo "Tag/Commit Date: $commit_date"
          echo "Current Time: $current_time"
          echo "24h ago threshold: $time_24h_ago"
          if [[ "$commit_date" > "$time_24h_ago" ]]; then
              echo "✅ New v* tag $latest_v_tag found in the last 24 hours."
              echo "proceed=true" >> $GITHUB_OUTPUT
          else
              echo "❌ No new v* tags found in the last 24 hours."
              echo "Latest v* tag is $latest_v_tag (${days}d ${hours}h ${minutes}m old)"
              echo "proceed=false" >> $GITHUB_OUTPUT
          fi

  react-jsonschema-form-bs4:
    needs: [check-new-v-tags]
    if: ${{ needs.check-new-v-tags.outputs.proceed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: react-jsonschema-form-bs4
        run: |
          git clone https://github.com/KEGustafsson/react-jsonschema-form-bs4.git
          cd react-jsonschema-form-bs4
          rm -f package-lock.json
          npm i
          npm pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          retention-days: 1
          name: react-jsonschema-form-bs4
          path: |
            ./react-jsonschema-form-bs4/*.tgz

  specification:
    needs: [check-new-v-tags]
    if: ${{ needs.check-new-v-tags.outputs.proceed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: specification
        run: |
          git clone https://github.com/SignalK/specification.git
          cd specification
          npm i
          npm pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          retention-days: 1
          name: specification
          path: |
            ./specification/*.tgz

  nmea0183-signalk:
    needs: [specification]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - uses: actions/download-artifact@v4
        with:
          name: specification
      - name: nmea0183-signalk
        run: |
          git clone https://github.com/SignalK/nmea0183-signalk.git
          cd nmea0183-signalk
          mv ../*.tgz .
          npm i --save *.tgz
          rm -rf node_modules
          rm -f package-lock.json
          rm -f *.tgz
          npm pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          retention-days: 1
          name: nmea0183-signalk
          path: |
            ./nmea0183-signalk/*.tgz

  signalk-server:
    needs: [nmea0183-signalk, react-jsonschema-form-bs4]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: signalk-server download and patch
        id: git
        run: |
          git clone https://github.com/SignalK/signalk-server.git
          cd signalk-server
          git fetch --tags
          tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "Extracted tag: $tag"
          if [ -d "./../patch" ] && [ "$(ls -A ./../patch/*.patch 2>/dev/null)" ]; then
            git apply ./../patch/*.patch
          else
            echo "No patches to apply"
          fi
      - uses: actions/download-artifact@v4
        with:
          name: react-jsonschema-form-bs4
      - name: server-admin-ui patch 
        run: |
          cd signalk-server/packages/server-admin-ui
          mv ./../../../*.tgz .
          npm i --save-dev *.tgz
          rm -rf node_modules
          rm -f package-lock.json
      - uses: actions/download-artifact@v4
        with:
          name: nmea0183-signalk
      - uses: actions/download-artifact@v4
        with:
          name: specification
      - name: signalk-server build
        run: |
          cd signalk-server
          mv ./../*.tgz .
          rm -f package-lock.json
          rm -rf node_modules
          npm cache clean -f
          npm install npm@latest -g
          npm install --package-lock-only
          npm ci && npm cache clean --force
          npm run build:all
          npm pack --workspaces
          rm signalk-typedoc-signalk-theme*.tgz # This is only needed as a dev dependency
          npm pack
      - name: Save tag to artifact
        run: echo ${{ steps.git.outputs.tag }} > tag.txt
      - name: Upload tag
        uses: actions/upload-artifact@v5
        with:
          retention-days: 1
          name: tag
          path: tag.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          retention-days: 1
          name: packed-modules
          path: ./signalk-server/*.tgz

  build_docker_tags:
    needs: [signalk-server]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [24.04]
        node: [22.x, 24.x]
        exclude:
          - node: 22.x
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tag
      - name: Set TAG for build-args
        id: vars
        run: |
          tag=$(cat tag.txt)
          echo "Extracted tag: $tag"
          echo "TAG=$tag" >> $GITHUB_OUTPUT
          IFS='.' read -r MAJOR MINOR PATCH <<< "$tag"
          echo "MAJOR=$MAJOR" >> $GITHUB_OUTPUT
          echo "MINOR=$MAJOR.$MINOR" >> $GITHUB_OUTPUT
          echo "ghcr=ghcr.io/kegustafsson/signalk-server" >> $GITHUB_OUTPUT
          echo "hub=kgustafs/signalk-server" >> $GITHUB_OUTPUT
      - name: Set tags
        id: set-tags
        run: |
          if [[ "${{ steps.vars.outputs.tag }}" == *beta* ]]; then
            tags="${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.TAG }}-${{ matrix.os }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:latest-${{ matrix.os }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.TAG }}-${{ matrix.os }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:latest-${{ matrix.os }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.TAG }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:latest-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.TAG }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:latest-${{ matrix.node }}"
          else
            tags="${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.TAG }}-${{ matrix.os }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.MAJOR }}-${{ matrix.os }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.MINOR }}-${{ matrix.os }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:latest-${{ matrix.os }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.TAG }}-${{ matrix.os }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.MAJOR }}-${{ matrix.os }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.MINOR }}-${{ matrix.os }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:latest-${{ matrix.os }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.TAG }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.MAJOR }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.MINOR }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:latest-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.TAG }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.MAJOR }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.MINOR }}-${{ matrix.node }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:latest-${{ matrix.node }}"
          fi
          echo "tags=$tags" >> $GITHUB_OUTPUT
      - name: Save docker tags to artifact
        run: echo ${{ steps.set-tags.outputs.tags }} > docker_tags_${{ matrix.os }}_${{ matrix.node }}.txt
      - name: Upload tag
        uses: actions/upload-artifact@v5
        with:
          retention-days: 1
          name: docker_tags_${{ matrix.os }}_${{ matrix.node }}
          path: docker_tags_${{ matrix.os }}_${{ matrix.node }}.txt

  build-images:
    needs: [signalk-server]
    strategy:
      matrix:
        os: [24.04]
        node: [22.x, 24.x]
        exclude:
          - node: 22.x
        vm: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - vm: ubuntu-latest
            os: 24.04
            arch: amd
            platform: linux/amd64
#          - vm: ubuntu-24.04-arm
#            os: 24.04
#            arch: arm
#            node: 22.x
#            platform: linux/arm64,linux/arm/v7
          - vm: ubuntu-24.04-arm
            os: 24.04
            arch: arm
            node: 24.x
            platform: linux/arm64
    runs-on: ${{ matrix.vm }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: packed-modules
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/kegustafsson/signalk-server:${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.node }}-${{ github.run_id }}
          build-args: |
            UBUNTU_VERSION=${{ matrix.os }}-${{ matrix.node }}

  create-and-push-manifest:
    needs: [build_docker_tags, build-images]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [24.04]
        node: [22.x, 24.x]
        exclude:
          - node: 22.x
        include:
          - os: 24.04
            node: 24.x
            tag: latest
#          - os: 24.04
#            node: 22.x
#            tag: latest-22.x
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/download-artifact@v4
        with:
          name: docker_tags_${{ matrix.os }}_${{ matrix.node }}
      - name: Set multi-line output
        id: set_images
        run: |
          tags=$(cat docker_tags_${{ matrix.os }}_${{ matrix.node }}.txt | sed 's/,/\n/g')
          {
            echo 'IMAGES<<EOF'
            printf "%s\n" "$tags"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      - name: Print tags
        run: |
          tags=$(cat docker_tags_${{ matrix.os }}_${{ matrix.node }}.txt | sed 's/,/\n/g')
          echo "tags: $tags"
          echo "tags: ${{ steps.set_images.outputs.IMAGES }}"      
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Create and push multi-arch manifest to GHCR and Docker Hub
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ steps.set_images.outputs.IMAGES }}
            ghcr.io/kegustafsson/signalk-server:${{ matrix.tag }}
            kgustafs/signalk-server:${{ matrix.tag }}
          sources: |
            ghcr.io/kegustafsson/signalk-server:amd-${{ matrix.os }}-${{ matrix.node }}-${{ github.run_id }}
            ghcr.io/kegustafsson/signalk-server:arm-${{ matrix.os }}-${{ matrix.node }}-${{ github.run_id }}

  housekeeping:
    needs: create-and-push-manifest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [24.04]
        node: [22.x, 24.x]
        exclude:
          - node: 22.x
    permissions:
      packages: write
    steps:
      - name: Remove Docker Image from GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: signalk-server
          delete-untagged: true
          delete-tags: amd-${{ matrix.os }}-${{ matrix.node }}-${{ github.run_id }},arm-${{ matrix.os }}-${{ matrix.node }}-${{ github.run_id }}
          token: ${{ secrets.GHCR_TOKEN_NEW }}

  slack:
    runs-on: ubuntu-latest
    needs: housekeeping
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: tag
      - name: Set TAG for build-args
        id: vars
        run: |
          tag=$(cat tag.txt)
          echo "Extracted tag: $tag"
          echo "TAG=$tag" >> $GITHUB_OUTPUT
      - name: Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"New Signal K image available, ${{ steps.vars.outputs.TAG }}"}' https://hooks.slack.com/services/${{ secrets.SLACK }}
