name: SignalK Docker Build - vanilla

on:
  workflow_dispatch:

jobs:
  specification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: specification
        run: |
          git clone https://github.com/SignalK/specification.git
          cd specification
          npm i
          npm pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: specification
          path: |
            ./specification/*.tgz

  nmea0183-signalk:
    needs: [specification]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - uses: actions/download-artifact@v4
        with:
          name: specification
      - name: nmea0183-signalk
        run: |
          git clone https://github.com/SignalK/nmea0183-signalk.git
          cd nmea0183-signalk
          mv ../*.tgz .
          npm i --save *.tgz
          rm -rf node_modules
          rm -f package-lock.json
          rm -f *.tgz
          npm pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: nmea0183-signalk
          path: |
            ./nmea0183-signalk/*.tgz

  signalk-server:
    needs: [nmea0183-signalk]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: signalk-server download and patch
        id: git
        run: |
          # git clone https://github.com/SignalK/signalk-server.git
          git clone -b fix https://github.com/KEGustafsson/signalk-server.git
          cd signalk-server
          git fetch --tags
          tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "Extracted tag: $tag"
      - uses: actions/download-artifact@v4
        with:
          name: nmea0183-signalk
      - uses: actions/download-artifact@v4
        with:
          name: specification
      - name: signalk-server build
        run: |
          cd signalk-server
          mv ./../*.tgz .
          rm -f package-lock.json
          rm -rf node_modules
          npm install --package-lock-only
          npm ci && npm cache clean --force
          npm run build:all
          for dir in packages/*; do
            pushd $dir && npm pack && mv *.tgz ../../ && popd
          done
          rm typedoc-signalk-theme*.tgz # This is only needed as a dev dependency
          npm pack
      - name: Save tag to artifact
        run: echo ${{ steps.git.outputs.tag }} > tag.txt
      - name: Upload tag
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: tag
          path: tag.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: packed-modules
          path: ./signalk-server/*.tgz

  build_docker_tags:
    needs: [signalk-server]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [22.04, 24.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tag
      - name: Set TAG for build-args
        id: vars
        run: |
          tag=$(cat tag.txt)
          echo "Extracted tag: $tag"
          echo "TAG=$tag" >> $GITHUB_OUTPUT
          IFS='.' read -r MAJOR MINOR PATCH <<< "$tag"
          echo "MAJOR=$MAJOR" >> $GITHUB_OUTPUT
          echo "MINOR=$MAJOR.$MINOR" >> $GITHUB_OUTPUT
          echo "ghcr=ghcr.io/kegustafsson/signalk-server" >> $GITHUB_OUTPUT
          echo "hub=kgustafs/signalk-server" >> $GITHUB_OUTPUT
      - name: Set tags
        id: set-tags
        run: |
          if [[ "${{ steps.vars.outputs.tag }}" == *beta* ]]; then
            tags="${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.TAG }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.TAG }}-${{ matrix.os }}"
          else
            tags="${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.TAG }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.MAJOR }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.MINOR }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:latest-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.TAG }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.MAJOR }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.MINOR }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:latest-${{ matrix.os }}"
          fi
          echo "tags=$tags" >> $GITHUB_OUTPUT
      - name: Save docker tags to artifact
        run: echo ${{ steps.set-tags.outputs.tags }} > docker_tags_${{ matrix.os }}.txt
      - name: Upload tag
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: docker_tags_${{ matrix.os }}
          path: docker_tags_${{ matrix.os }}.txt

  build-images:
    needs: [signalk-server]
    strategy:
      matrix:
        os: [22.04, 24.04]
        vm: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - vm: ubuntu-latest
            arch: amd
            platform: linux/amd64
          - vm: ubuntu-24.04-arm
            arch: arm
            platform: linux/arm64,linux/arm/v7
    runs-on: ${{ matrix.vm }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: packed-modules
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Modify Dockerfile for build
        run: |
          sed -i \
            "s|:latest|:latest-${{ matrix.os }}|g" \
            ./docker/Dockerfile
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/kegustafsson/signalk-server:${{ matrix.arch }}-${{ matrix.os }}-${{ github.run_id }}

  create-and-push-manifest:
    needs: [build_docker_tags, build-images]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [22.04, 24.04]
        include:
          - os: 24.04
            tag: latest
          - os: 22.04
            tag: latest-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/download-artifact@v4
        with:
          name: docker_tags_${{ matrix.os }}
      - name: Set multi-line output
        id: set_images
        run: |
          tags=$(cat docker_tags_${{ matrix.os }}.txt | sed 's/,/\n/g')
          {
            echo 'IMAGES<<EOF'
            printf "%s\n" "$tags"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Create and push multi-arch manifest to GHCR and Docker Hub
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ steps.set_images.outputs.IMAGES }}
            ghcr.io/kegustafsson/signalk-server:${{ matrix.tag }}
            kgustafs/signalk-server:${{ matrix.tag }}
          sources: |
            ghcr.io/kegustafsson/signalk-server:amd-${{ matrix.os }}-${{ github.run_id }}
            ghcr.io/kegustafsson/signalk-server:arm-${{ matrix.os }}-${{ github.run_id }}

  housekeeping:
    needs: create-and-push-manifest
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Remove Docker Image from GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: signalk-server
          delete-untagged: true
          delete-tags: amd-22.04-${{ github.run_id }},arm-22.04-${{ github.run_id }},amd-24.04-${{ github.run_id }},arm-24.04-${{ github.run_id }}
          token: ${{ secrets.GHCR_TOKEN_NEW }}

  slack:
    runs-on: ubuntu-latest
    needs: housekeeping
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: tag
      - name: Set TAG for build-args
        id: vars
        run: |
          tag=$(cat tag.txt)
          echo "Extracted tag: $tag"
          echo "TAG=$tag" >> $GITHUB_OUTPUT
      - name: Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Manually triggered image ready, ${{ steps.vars.outputs.TAG }}"}' https://hooks.slack.com/services/${{ secrets.SLACK }}
