name: Housekeeping

on:
  workflow_dispatch:

jobs:
  housekeeping:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [22.04, 24.04]

    steps:	
      - name: Delete Docker Hub Tag
        env:
          IMAGE_NAME: "kgustafs/signalk-server-base"
          TAG1: "amd-${{ matrix.os }}"
          TAG2: "arm-${{ matrix.os }}"
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST \
            -d '{"username": "${{ secrets.DOCKER_HUB_USERNAME }}", "password": "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          curl -X DELETE \
            -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/$IMAGE_NAME/tags/$TAG1/"
          curl -X DELETE \
            -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/$IMAGE_NAME/tags/$TAG2/"
            
      - name: Remove Docker Image from GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: signalk-server-base
          delete-untagged: true
          delete-tags: amd-${{ matrix.os }},arm-${{ matrix.os }}
          token: ${{ secrets.GHCR_TOKEN_NEW }}
