name: Build Docker base images v3

on:
  workflow_dispatch:

jobs:
  setup-local-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Set up local registry
        run: |
          docker run -d -p 5000:5000 --name registry registry:2
      - name: Verify local registry
        run: |
          until curl -s http://localhost:5000/v2/; do
            echo "Waiting for local registry to be available..."
            sleep 2
          done

  setup-local-registry-test:
    runs-on: ubuntu-latest
    steps:
      - name: Verify local registry
        run: |
          until curl -s http://localhost:5000/v2/; do
            echo "Waiting for local registry to be available..."
            sleep 2
          done

  build-images:
    needs: setup-local-registry-test
    strategy:
      matrix:
        os: [22.04, 24.04]
        vm: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - vm: ubuntu-latest
            arch: amd
            platform: linux/amd64
          - vm: ubuntu-24.04-arm
            arch: arm
            platform: linux/arm64,linux/arm/v7
    runs-on: ${{ matrix.vm }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build baseimages
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_base_${{ matrix.os }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            localhost:5000/signalk-server-base:${{ matrix.arch }}-${{ matrix.os }}

      - name: Modify Dockerfile_rel for testing
        run: |
          sed -i \
            "s|ghcr.io/kegustafsson/signalk-server-base:latest|localhost:5000/signalk-server-base:${{ matrix.arch }}-${{ matrix.os }}|g" \
            ./docker/Dockerfile_rel  

      - name: Build Signal K test docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_rel
          platforms: ${{ matrix.platform }}
          build-args: |
            TAG=latest

  create-and-push-manifest:
    needs: [build-images]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [22.04, 24.04]

    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create and push multi-arch manifest to GHCR and Docker Hub
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ghcr.io/kegustafsson/signalk-server-base:latest-${{ matrix.os }}
            kgustafs/signalk-server-base:latest-${{ matrix.os }}
          sources: |
            localhost:5000/signalk-server-base:amd-${{ matrix.os }}
            localhost:5000/signalk-server-base:arm-${{ matrix.os }}

  slack:
    runs-on: ubuntu-latest
    needs: create-and-push-manifest
    steps:
      - name: Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Ubuntu 22.04 and 24.04 base images ready"}' https://hooks.slack.com/services/${{ secrets.SLACK }}
