name: Build Docker base container 22.04 amd and arm parallel

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build baseimages
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_base_22.04
          platforms: linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/kegustafsson/signalk-server-base:arm-22.04
            kgustafs/signalk-server-base:arm-22.04

      - name: Modify Dockerfile_rel_22.04 for testing
        run: |
          sed -i 's/:latest-22.04/:arm-22.04/g' ./docker/Dockerfile_rel_22.04

      - name: Build Signal K test docker for arm
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_rel_22.04
          platforms: linux/arm64,linux/arm/v7
          build-args: |
            TAG=latest

  build-amd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build baseimages
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_base_22.04
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/kegustafsson/signalk-server-base:amd-22.04
            kgustafs/signalk-server-base:amd-22.04
            
      - name: Modify Dockerfile_rel_22.04 for testing
        run: |
          sed -i 's/:latest-22.04/:amd-22.04/g' ./docker/Dockerfile_rel_22.04

      - name: Build Signal K test docker for amd
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_rel_22.04
          platforms: linux/amd64
          build-args: |
            TAG=latest

  create-and-push-manifest:
    needs: [build-arm, build-amd]
    runs-on: ubuntu-latest

    steps:	
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create and push multi-arch manifest to GHCR and Docker Hub
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ghcr.io/kegustafsson/signalk-server-base:latest-22.04
            kgustafs/signalk-server-base:latest-22.04
          sources: |
            ghcr.io/kegustafsson/signalk-server-base:amd-22.04
            ghcr.io/kegustafsson/signalk-server-base:arm-22.04
            kgustafs/signalk-server-base:amd-22.04			
            kgustafs/signalk-server-base:arm-22.04

  housekeeping:
    needs: create-and-push-manifest
    runs-on: ubuntu-latest
    
    steps:	
      - name: Delete Docker Hub Tag
        env:
          IMAGE_NAME: "kgustafs/signalk-server-base"
          TAG1: "amd-22.04"
          TAG2: "arm-22.04"
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST \
            -d '{"username": "${{ secrets.DOCKER_HUB_USERNAME }}", "password": "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          curl -X DELETE \
            -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/$IMAGE_NAME/tags/$TAG1/"
          curl -X DELETE \
            -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/$IMAGE_NAME/tags/$TAG2/"
            
      - name: Remove Docker Image from GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: signalk-server-base
          delete-untagged: true
          delete-tags: amd-22.04,arm-22.04
          token: ${{ secrets.GHCR_TOKEN_NEW }}

  slack:
    runs-on: ubuntu-latest
    needs: housekeeping
    steps:
      - name: Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Ubuntu 22.04 base image built"}' https://hooks.slack.com/services/${{ secrets.SLACK }}
