name: SignalK Docker Build 24h v3

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  check-new-v-tags:
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.check.outputs.proceed }}
    
    steps:
      - name: Fetch and compare tags
        id: check
        run: |
          EXTERNAL_REPO="SignalK/signalk-server"
          tags=$(curl -s "https://api.github.com/repos/$EXTERNAL_REPO/tags" | grep -o '"name": *"[^"]*"' | sed -E 's/.*"name": *"([^"]*)".*/\1/' | tr '\n' ' ')
          echo "Fetched tags: $tags"
          if [ $? -ne 0 ] || [ -z "$tags" ]; then
            echo "Failed to fetch tags or no tags found."
            exit 0
          fi
          latest_v_tag=$(echo "$tags" | grep '^v' | head -n 1)
          echo "Latest v* tag: $latest_v_tag"
          if [ -z "$latest_v_tag" ]; then
            echo "No tags starting with 'v' found."
            exit 0
          fi
          tag_details=$(curl -s "https://api.github.com/repos/$EXTERNAL_REPO/git/refs/tags/$latest_v_tag")
          echo "Tag details: $tag_details"
          commit_sha=$(echo "$tag_details" | grep -o '"sha": *"[^"]*"' | sed -E 's/.*"sha": *"([^"]*)".*/\1/')
          commit_date=$(echo "$tag_details" | grep -o '"url": *"[^"]*"' | sed -E 's/.*"url": *"([^"]*)".*/\1/' | xargs -I {} curl -s {} | grep -o '"date": *"[^"]*"' | sed -E 's/.*"date": *"([^"]*)".*/\1/')
          echo "Commit SHA: $commit_sha"
          echo "Tag date: $commit_date"
          if [ -z "$commit_sha" ] || [ "$commit_sha" == "null" ]; then
            echo "Failed to fetch commit SHA for tag."
            exit 1
          fi
          if [ -z "$commit_date" ] || [ "$commit_date" == "null" ]; then
            echo "Failed to fetch tag date."
            exit 1
          fi
          current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "Action runtime date and time: $current_time"
          echo "Tag date and time: $commit_date"
          commit_epoch=$(date -u -d "$commit_date" +%s)
          current_epoch=$(date -u -d "$current_time" +%s)
          time_diff_seconds=$((current_epoch - commit_epoch))
          days=$((time_diff_seconds / 86400))
          hours=$(( (time_diff_seconds % 86400) / 3600 ))
          minutes=$(( (time_diff_seconds % 3600) / 60 ))
          seconds=$((time_diff_seconds % 60))
          echo "Time difference: ${days}d ${hours}h ${minutes}m ${seconds}s"
          time_24h_ago=$(date -u -d "$current_time - 24 hours" +"%Y-%m-%dT%H:%M:%SZ")
          echo "Time 24 hours ago: $time_24h_ago"
          if [[ "$commit_date" > "$time_24h_ago" ]]; then
            echo "New v* tag $latest_v_tag found in the last 24 hours."
            echo "proceed=true" >> $GITHUB_OUTPUT
          else
            echo "No new v* tags found in the last 24 hours."
            echo "proceed=false" >> $GITHUB_OUTPUT
            exit 0
          fi

  react-jsonschema-form-bs4:
    needs: [check-new-v-tags]
    if: ${{ needs.check-new-v-tags.outputs.proceed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: react-jsonschema-form-bs4
        run: |
          git clone https://github.com/KEGustafsson/react-jsonschema-form-bs4.git
          cd react-jsonschema-form-bs4
          rm -f package-lock.json
          npm i
          npm pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: react-jsonschema-form-bs4
          path: |
            ./react-jsonschema-form-bs4/*.tgz

  specification:
    needs: [check-new-v-tags]
    if: ${{ needs.check-new-v-tags.outputs.proceed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: specification
        run: |
          git clone https://github.com/SignalK/specification.git
          cd specification
          npm i
          npm pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: specification
          path: |
            ./specification/*.tgz

  nmea0183-signalk:
    needs: [specification]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - uses: actions/download-artifact@v4
        with:
          name: specification
      - name: nmea0183-signalk
        run: |
          git clone https://github.com/SignalK/nmea0183-signalk.git
          cd nmea0183-signalk
          mv ../*.tgz .
          npm i --save *.tgz
          rm -rf node_modules
          rm -f package-lock.json
          rm -f *.tgz
          npm pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: nmea0183-signalk
          path: |
            ./nmea0183-signalk/*.tgz

  signalk-server:
    needs: [nmea0183-signalk, react-jsonschema-form-bs4]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: signalk-server download and patch
        id: git
        run: |
          git clone https://github.com/SignalK/signalk-server.git
          cd signalk-server
          git fetch --tags
          tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "Extracted tag: $tag"
          if [ -d "./../patch" ] && [ "$(ls -A ./../patch/*.patch 2>/dev/null)" ]; then
            git apply ./../patch/*.patch
          else
            echo "No patches to apply"
          fi
      - uses: actions/download-artifact@v4
        with:
          name: react-jsonschema-form-bs4
      - name: server-admin-ui patch 
        run: |
          cd signalk-server/packages/server-admin-ui
          mv ./../../../*.tgz .
          npm i --save-dev *.tgz
          rm -rf node_modules
          rm -f package-lock.json
      - uses: actions/download-artifact@v4
        with:
          name: nmea0183-signalk
      - uses: actions/download-artifact@v4
        with:
          name: specification
      - name: signalk-server build
        run: |
          cd signalk-server
          mv ./../*.tgz .
          rm -f package-lock.json
          rm -rf node_modules
          npm install --package-lock-only
          npm ci && npm cache clean --force
          npm run build --workspaces --if-present
          cd packages/server-admin-ui
          rm -f *.tgz
          npm pack && mv *.tgz ../../
          cd ../server-api
          npm pack && mv *.tgz ../../
          cd ../streams
          npm pack && mv *.tgz ../../
          cd ../..
          jq '.workspaces=[]' package.json > _package.json && mv _package.json package.json
          npm i --save *.tgz
          npm run build
          npm pack
      - name: Save tag to artifact
        run: echo ${{ steps.git.outputs.tag }} > tag.txt
      - name: Upload tag
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: tag
          path: tag.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: packed-modules
          path: ./signalk-server/*.tgz

  build_docker_tags:
    needs: [signalk-server]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [22.04, 24.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tag
      - name: Set TAG for build-args
        id: vars
        run: |
          tag=$(cat tag.txt)
          echo "Extracted tag: $tag"
          echo "TAG=$tag" >> $GITHUB_OUTPUT
          IFS='.' read -r MAJOR MINOR PATCH <<< "$tag"
          echo "MAJOR=$MAJOR" >> $GITHUB_OUTPUT
          echo "MINOR=$MAJOR.$MINOR" >> $GITHUB_OUTPUT
          echo "ghcr=ghcr.io/kegustafsson/signalk-server" >> $GITHUB_OUTPUT
          echo "hub=kgustafs/signalk-server" >> $GITHUB_OUTPUT
      - name: Set tags
        id: set-tags
        run: |
          if [[ "${{ steps.vars.outputs.tag }}" == *beta* ]]; then
            tags="${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.TAG }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.TAG }}-${{ matrix.os }}"
          else
            tags="${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.TAG }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.MAJOR }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:${{ steps.vars.outputs.MINOR }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.ghcr }}:latest-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.TAG }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.MAJOR }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:${{ steps.vars.outputs.MINOR }}-${{ matrix.os }}"
            tags="$tags,${{ steps.vars.outputs.hub }}:latest-${{ matrix.os }}"
          fi
          echo "tags=$tags" >> $GITHUB_OUTPUT
      - name: Save docker tags to artifact
        run: echo ${{ steps.set-tags.outputs.tags }} > docker_tags_${{ matrix.os }}.txt
      - name: Upload tag
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: docker_tags_${{ matrix.os }}
          path: docker_tags_${{ matrix.os }}.txt

  build-images:
    needs: [signalk-server]
    strategy:
      matrix:
        os: [22.04, 24.04]
        vm: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - vm: ubuntu-latest
            arch: amd
            platform: linux/amd64
          - vm: ubuntu-24.04-arm
            arch: arm
            platform: linux/arm64,linux/arm/v7
    runs-on: ${{ matrix.vm }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: packed-modules
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Modify Dockerfile for build
        run: |
          sed -i \
            "s|:latest|:latest-${{ matrix.os }}|g" \
            ./docker/Dockerfile
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/kegustafsson/signalk-server:${{ matrix.arch }}-${{ matrix.os }}-${{ github.run_id }}

  create-and-push-manifest:
    needs: [build_docker_tags, build-images]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [22.04, 24.04]
        include:
          - os: 24.04
            tag: latest
          - os: 22.04
            tag: latest-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/download-artifact@v4
        with:
          name: docker_tags_${{ matrix.os }}
      - name: Set multi-line output
        id: set_images
        run: |
          tags=$(cat docker_tags_${{ matrix.os }}.txt | sed 's/,/\n/g')
          {
            echo 'IMAGES<<EOF'
            printf "%s\n" "$tags"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Create and push multi-arch manifest to GHCR and Docker Hub
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ steps.set_images.outputs.IMAGES }}
            ghcr.io/kegustafsson/signalk-server:${{ matrix.tag }}
            kgustafs/signalk-server:${{ matrix.tag }}
          sources: |
            ghcr.io/kegustafsson/signalk-server:amd-${{ matrix.os }}-${{ github.run_id }}
            ghcr.io/kegustafsson/signalk-server:arm-${{ matrix.os }}-${{ github.run_id }}

  housekeeping:
    needs: create-and-push-manifest
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Remove Docker Image from GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: signalk-server
          delete-untagged: true
          delete-tags: amd-22.04-${{ github.run_id }},arm-22.04-${{ github.run_id }},amd-24.04-${{ github.run_id }},arm-24.04-${{ github.run_id }}
          token: ${{ secrets.GHCR_TOKEN_NEW }}

  slack:
    runs-on: ubuntu-latest
    needs: housekeeping
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: tag
      - name: Set TAG for build-args
        id: vars
        run: |
          tag=$(cat tag.txt)
          echo "Extracted tag: $tag"
          echo "TAG=$tag" >> $GITHUB_OUTPUT
      - name: Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"New Signal K image available, ${{ steps.vars.outputs.TAG }}"}' https://hooks.slack.com/services/${{ secrets.SLACK }}
