name: Build Docker base images v2

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build-images:
    strategy:
      matrix:
        os: [22.04, 24.04]
        vm: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - vm: ubuntu-latest
            arch: amd64
            platform: linux/amd64
          - vm: ubuntu-24.04-arm
            arch: arm64
            platform: linux/arm64
          - vm: ubuntu-24.04-arm
            arch: armv7
            platform: linux/arm/v7
    runs-on: ${{ matrix.vm }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build baseimages
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_base_${{ matrix.os }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/kegustafsson/signalk-server-base:${{ matrix.arch }}-${{ matrix.os }}
            kgustafs/signalk-server-base:${{ matrix.arch }}-${{ matrix.os }}

      - name: Modify Dockerfile_rel for testing
        run: |
          sed -i "s/:latest/:${{ matrix.arch }}-${{ matrix.os }}/g" ./docker/Dockerfile_rel

      - name: Build Signal K test docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile_rel
          platforms: ${{ matrix.platform }}
          build-args: |
            TAG=latest

  create-and-push-manifest:
    needs: [build-images]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [22.04, 24.04]

    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create and push multi-arch manifest to GHCR and Docker Hub
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ghcr.io/kegustafsson/signalk-server-base:latest-${{ matrix.os }}
            kgustafs/signalk-server-base:latest-${{ matrix.os }}
          sources: |
            ghcr.io/kegustafsson/signalk-server-base:amd64-${{ matrix.os }}
            ghcr.io/kegustafsson/signalk-server-base:arm64-${{ matrix.os }}
            ghcr.io/kegustafsson/signalk-server-base:armv7-${{ matrix.os }}
            kgustafs/signalk-server-base:amd64-${{ matrix.os }}
            kgustafs/signalk-server-base:arm64-${{ matrix.os }}
            kgustafs/signalk-server-base:armv7-${{ matrix.os }}

  housekeeping:
    needs: create-and-push-manifest
    runs-on: ubuntu-latest

    steps:
      - name: Delete Docker Hub Tag
        env:
          IMAGE_NAME: "kgustafs/signalk-server-base"
          TAG1: "amd64-22.04"
          TAG2: "arm64-22.04"
          TAG3: "armv7-22.04"
          TAG4: "amd64-24.04"
          TAG5: "arm64-24.04"
          TAG6: "armv7-24.04"
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          TOKEN=$(curl -s -H "Content-Type: application/json" -X POST \
            -d '{"username": "${{ secrets.DOCKER_HUB_USERNAME }}", "password": "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          for TAG in $TAG1 $TAG2 $TAG3 $TAG4 $TAG5 $TAG6; do
            curl -X DELETE \
              -H "Authorization: JWT $TOKEN" \
              "https://hub.docker.com/v2/repositories/$IMAGE_NAME/tags/$TAG/"
          done
            
      - name: Remove Docker Image from GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: signalk-server-base
          delete-untagged: true
          delete-tags: amd64-22.04,arm64-22.04,armv7-22.04,amd64-24.04,arm64-24.04,armv7-24.04
          token: ${{ secrets.GHCR_TOKEN_NEW }}

  slack:
    runs-on: ubuntu-latest
    needs: housekeeping
    steps:
      - name: Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Ubuntu 22.04 and 24.04 base images ready"}' https://hooks.slack.com/services/${{ secrets.SLACK }}
