name: Build Docker base images, new

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build-images:
    strategy:
      matrix:
        os: [24.04]
        node: [v22, v24]
        vm: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - vm: ubuntu-latest
            arch: amd
            platform: linux/amd64
          - vm: ubuntu-24.04-arm
            arch: arm
            node: v22
            platform: linux/arm64,linux/arm/v7
          - vm: ubuntu-24.04-arm
            arch: arm
            node: v24
            platform: linux/arm64
    runs-on: ${{ matrix.vm }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build baseimages
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile_base_${{ matrix.os }}_${{ matrix.node }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/kegustafsson/signalk-server-base:${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.node }}

      - name: Modify Dockerfile_rel for testing
        run: |
          sed -i \
            "s|:latest|:${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.node }}|g" \
            ./docker/Dockerfile_rel  

      - name: Build Signal K test docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile_rel
          platforms: ${{ matrix.platform }}
          build-args: |
            TAG=latest

  create-and-push-manifest:
    needs: [build-images]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [24.04]
        node: [v22, v24]

    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Create and push multi-arch manifest to GHCR and Docker Hub
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ghcr.io/kegustafsson/signalk-server-base:latest-${{ matrix.os }}-${{ matrix.node }}
            kgustafs/signalk-server-base:latest-${{ matrix.os }}-${{ matrix.node }}
          sources: |
            ghcr.io/kegustafsson/signalk-server-base:amd-${{ matrix.os }}-${{ matrix.node }}
            ghcr.io/kegustafsson/signalk-server-base:arm-${{ matrix.os }}-${{ matrix.node }}

  housekeeping:
    needs: create-and-push-manifest
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Remove Docker Image from GHCR
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: signalk-server-base
          delete-untagged: true
          delete-tags: amd-24.04-v22,arm-24.04-v24
          token: ${{ secrets.GHCR_TOKEN_NEW }}

  slack:
    runs-on: ubuntu-latest
    needs: housekeeping
    steps:
      - name: Slack notification
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Ubuntu 24.04 and Node v22 & v24 base images ready"}' https://hooks.slack.com/services/${{ secrets.SLACK }}
