name: Release - build & publish modules and server, build & publish docker containers

on:
  workflow_dispatch:

jobs:
  build_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          echo "Cloning and building server modules"
          git clone https://github.com/SignalK/signalk-server.git
          cd signalk-server
          echo "---------------------------------------------------"
          echo "building server-admin-ui-dependencies"
          cd packages/server-admin-ui-dependencies
          npm install --package-lock-only
          npm ci && npm cache clean --force
          #npm publish --access public
          echo "---------------------------------------------------"
          echo "building server-admin-ui"
          cd ../server-admin-ui
          npm install --package-lock-only
          npm ci && npm cache clean --force
          #npm publish --access public
          echo "---------------------------------------------------"
          echo "building server-api"
          cd ../server-api
          npm install --package-lock-only
          npm ci && npm cache clean --force
          #npm publish --access public
          echo "---------------------------------------------------"
          echo "building server-plugin"
          cd ../streams
          npm install --package-lock-only
          npm ci && npm cache clean --force
          #npm publish --access public
          echo "---------------------------------------------------"
          echo "building server-prvider-plugin"
          cd ../resources-provider-plugin
          npm install --package-lock-only
          npm ci && npm cache clean --force
          #npm publish --access public
          echo "---------------------------------------------------"
          echo "building signalkserver"          
          cd ../..
          npm install --package-lock-only
          npm ci && npm cache clean --force
          echo "---------------------------------------------------"
